#pragma config(Motor,  port1,           ArmMotor,      tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           leftmotor,     tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          rightmotor,    tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main ()
{

while(1 ==1){
	motor[rightmotor]= vexRT[Ch2]
	motor[leftmotor]= vexRT[Ch3]

	if(vexRT[Btn7U]==1){
			motor[ArmMotor]=-127;
	}
	else if(vexRT[Btn7D] ==1){
		motor[ArmMotor]= 127;
	}
	else{
		motor[ArmMotor]=0;
	}
	if(vexRT[Btn8U]==1){
		motor[Servo]= 127;
	}
	else if(vexRT[Btn8D]==1){
		motor[Servo] = -127;
	}
	else{
		motor[Servo]= 0;
	}


}


}

